Repository RedisGrafana/grafana-redis-datasource, pull requests merged in 2020-08, with the labels that each got.

#31 Added docker cmd line option to start
  README.md
Labels: documentation

#35 How to query a specific db inside same redis single node
  README.md
Labels: documentation

#37 Use "ScopedVars" when applying template variables.
  src/DataSource.ts
  src/plugin.json
Labels: enhancement

#40 Fix slowlog issue prior to Redis 4.0
  pkg/commands.go
Labels: bug

#41 Fix backend lint issues
  README.md
  package.json
  pkg/commands.go
  pkg/grafana-redis-datasource.go
Labels: bug

#42 Refactoring to support new commands and modules
  .circleci/config.yml
  .prettierignore
  .prettierrc.js
  appveyor.yml
  debug.sh
  package.json
  pkg/commands.go
  pkg/datasource.go
  pkg/datasource_test.go
  pkg/redis-custom.go
  pkg/redis-hash.go
  pkg/redis-info.go
  pkg/redis-query.go
  pkg/redis-set.go
  pkg/redis-stream.go
  pkg/redis-time-series.go
  src/DataSource.ts
  src/components/ConfigEditor.tsx
  src/components/QueryEditor.tsx
  src/components/index.ts
  src/module.test.ts
  src/module.ts
  src/redis/command.ts
  src/redis/index.ts
  src/redis/info.ts
  src/redis/query.ts
  src/redis/time-series.ts
  src/types.ts
  tsconfig.json
Labels: enhancement

#45 Add support for TS.GET, TS.INFO and TS.QUERYINDEX commands
  pkg/data-frame.go
  pkg/redis-custom.go
  pkg/redis-query.go
  pkg/redis-time-series.go
  src/redis/command.ts
Labels: enhancement

#46 Use bitbucket.org/creachadair/shell to parse Time-Series filter and custom query
  go.mod
  go.sum
  pkg/redis-custom.go
  pkg/redis-time-series.go
Labels: bug

#49 Add Redis dashboard to support multiple Redis instances
  dashboards/redis.json
Labels: enhancement

#52 Add Redis Cluster support and update monitoring dashboard
  .gitignore
  .prettierignore
  dashboards/redis.json
  pkg/datasource.go
  pkg/query.go
  pkg/redis-cluster.go
  pkg/redis-custom.go
  pkg/redis-hash.go
  pkg/redis-info.go
  pkg/redis-set.go
  pkg/redis-stream.go
  pkg/redis-time-series.go
  pkg/types.go
  src/components/ConfigEditor.tsx
  src/dashboards/redis.json
  src/redis/command.ts
  src/types.ts
Labels: enhancement

#54 Support Sentinel Client and README updates
  README.md
  pkg/datasource.go
  pkg/types.go
  src/components/ConfigEditor.tsx
  src/img/datasource.png
  src/img/redis-dashboard.png
  src/types.ts
Labels: enhancement

#53 MRANGE: add fill zero option
  pkg/redis-time-series.go
  src/redis/command.ts
Labels: enhancement

#57 Add Streaming capabilities to visualize INFO command
  README.md
  src/DataSource.ts
  src/components/QueryEditor.tsx
  src/dashboards/redis-streaming.json
  src/img/query.png
  src/img/redis-streaming.png
  src/plugin.json
  src/redis/query.ts
Labels: enhancement

#59 Support Connecting to Redis via Unix Socket
  pkg/datasource.go
  src/components/ConfigEditor.tsx
  src/types.ts
Labels: enhancement

#60 Support Redis 6 ACL authentication
  pkg/datasource.go
  pkg/types.go
  src/components/ConfigEditor.tsx
  src/img/datasource.png
  src/types.ts
Labels: enhancement
