Repository RedisGrafana/grafana-redis-datasource, pull requests merged in 2021-01, with the labels that each got.

#120 Add Empty Array when no values returned similar to redis-cli
  pkg/redis-custom.go
Labels: enhancement

#121 Add Empty Array when no values returned similar to redis-cli
  pkg/redis-custom.go
Labels: enhancement

#122 Add test data for backend testing
  .gitignore
  data/dump.rdb
  docker-compose-dev.yml
  provisioning/dashboards/data-types.json
  provisioning/dashboards/default.yaml
  provisioning/datasources/redis.yaml
Labels: enhancement

#124 Update CHANGELOG for version 1.3.0
  CHANGELOG.md
Labels: documentation

#123 Add unit tests
  .github/workflows/ci.yml
  .github/workflows/main.yml
  Magefile.go
  README.md
  data/dump.rdb
  go.mod
  go.sum
  package.json
  pkg/data-frame.go
  pkg/data-frame_test.go
  pkg/query_test.go
  pkg/redis-cluster_test.go
  pkg/redis-custom_test.go
  pkg/redis-hash_test.go
  pkg/redis-info.go
  pkg/redis-info_test.go
  pkg/redis-search.go
  pkg/redis-search_test.go
  pkg/redis-set_test.go
  pkg/redis-stream.go
  pkg/redis-stream_test.go
  pkg/redis-time-series.go
  pkg/redis-time-series_test.go
  pkg/testing-utilities_test.go
  provisioning/dashboards/data-types.json
Labels: enhancement

#125 Remove "Unknown command" error from response for custom panels
  package.json
  pkg/query.go
  pkg/query_test.go
Labels: enhancement

#126 Update CHANGELOG and version 1.3.1 bump
  CHANGELOG.md
  package.json
Labels: documentation

#128 Update Radix to 3.7.0 and other backend dependencies
  go.mod
  go.sum
Labels: enhancement

#129 Redis client refactoring, unit-tests refactoring and new unit-tests.
  pkg/data-frame.go
  pkg/data-frame_test.go
  pkg/datasource.go
  pkg/datasource_test.go
  pkg/query.go
  pkg/query_test.go
  pkg/redis-client.go
  pkg/redis-client_test.go
  pkg/redis-cluster.go
  pkg/redis-cluster_test.go
  pkg/redis-custom.go
  pkg/redis-custom_test.go
  pkg/redis-hash.go
  pkg/redis-hash_test.go
  pkg/redis-info.go
  pkg/redis-info_test.go
  pkg/redis-search.go
  pkg/redis-search_test.go
  pkg/redis-set.go
  pkg/redis-set_test.go
  pkg/redis-stream.go
  pkg/redis-stream_test.go
  pkg/redis-time-series.go
  pkg/redis-time-series_test.go
  pkg/testing-utilities_test.go
  pkg/types.go
Labels: enhancement

#135 Implement CLI-mode similar to Redis-cli
  pkg/redis-custom.go
  pkg/redis-custom_test.go
  pkg/types.go
Labels: enhancement

#137 Added support for errorstats features coming in redis 6.2; Extended commandstats fields with failedCalls and rejectedCalls
  pkg/redis-info.go
  pkg/redis-info_test.go
  src/redis/info.ts
Labels: enhancement

#138 Implementing new tmscan (type + memory scan) command
  Magefile.go
  docker-compose-test.yml
  package.json
  pkg/query.go
  pkg/query_test.go
  pkg/redis-client.go
  pkg/redis-client_test.go
  pkg/redis-tmscan.go
  pkg/redis-tmscan_integration_test.go
  pkg/redis-tmscan_test.go
  pkg/testing-utilities_integration_test.go
  pkg/testing-utilities_test.go
  pkg/types.go
  provisioning/dashboards/data-types.json
  src/components/query-editor.tsx
  src/redis/command.ts
  src/redis/query.ts
Labels: enhancement

#140 Implement new RG.* commands
  data/dump.rdb
  pkg/query.go
  pkg/query_test.go
  pkg/redis-gears.go
  pkg/redis-gears_integration_test.go
  pkg/redis-gears_test.go
  pkg/testing-utilities_test.go
  provisioning/dashboards/data-types.json
  src/components/query-editor.test.tsx
  src/components/query-editor.tsx
  src/redis/command.ts
  src/redis/query.ts
Labels: enhancement

#141 Upgrade Grafana SDK to 0.83
  go.mod
  go.sum
Labels: enhancement

#143 Update tests and frontend components
  pkg/data-frame_test.go
  pkg/datasource_test.go
  pkg/query.go
  pkg/query_test.go
  pkg/redis-client_test.go
  pkg/redis-cluster_test.go
  pkg/redis-gears.go
  pkg/redis-gears_integration_test.go
  pkg/redis-hash_test.go
  pkg/redis-search_test.go
  pkg/redis-set_test.go
  pkg/redis-stream_test.go
  pkg/redis-tmscan_integration_test.go
  pkg/redis-tmscan_test.go
  pkg/testing-utilities_integration_test.go
  src/components/config-editor/config-editor.test.tsx
  src/components/config-editor/config-editor.tsx
  src/components/config-editor/index.ts
  src/components/query-editor/index.ts
  src/components/query-editor/query-editor.test.tsx
  src/components/query-editor/query-editor.tsx
  src/redis/command.ts
Labels: enhancement

#144 Tmscan improvements
  Magefile.go
  pkg/redis-tmscan.go
  pkg/redis-tmscan_integration_test.go
  pkg/redis-tmscan_test.go
  pkg/types.go
  provisioning/dashboards/data-types.json
  src/components/query-editor/query-editor.tsx
  src/redis/command.ts
  src/redis/query.ts
Labels: enhancement

#145 Rework TMSCAN and related tests, Implement rg.pyexecute
  pkg/query.go
  pkg/query_test.go
  pkg/redis-gears.go
  pkg/redis-gears_integration_test.go
  pkg/redis-gears_test.go
  pkg/redis-tmscan.go
  pkg/redis-tmscan_integration_test.go
  pkg/redis-tmscan_test.go
  src/redis/command.ts
Labels: enhancement

#146 Fix tmscan tests, add new params for PYEXECUTE, rework XINFO
  data/dump.rdb
  pkg/redis-gears.go
  pkg/redis-gears_integration_test.go
  pkg/redis-gears_test.go
  pkg/redis-stream.go
  pkg/redis-stream_integration_test.go
  pkg/redis-stream_test.go
  pkg/redis-tmscan_integration_test.go
  pkg/testing-utilities_test.go
  pkg/types.go
  provisioning/dashboards/data-types.json
  src/redis/command.ts
Labels: enhancement

#148 Implement XRANGE and XREVRANGE
  .gitignore
  docker-compose-dev.yml
  docker-compose.yml
  pkg/query.go
  pkg/query_test.go
  pkg/redis-stream.go
  pkg/redis-stream_integration_test.go
  pkg/redis-stream_test.go
  pkg/types.go
  provisioning/dashboards/data-types.json
  src/components/query-editor/query-editor.tsx
  src/redis/command.ts
  src/redis/index.ts
  src/redis/query.ts
  src/redis/types.ts
Labels: enhancement

#149 Add Client Type tooltip
  pkg/redis-custom_test.go
  src/components/config-editor/config-editor.test.tsx
  src/components/config-editor/config-editor.tsx
  src/constants.ts
  src/data-source.test.ts
  src/types.ts
Labels: enhancement

#150 Fix RG.DUMPREGISTRATIONS command to accept args with array
  pkg/redis-gears.go
  pkg/redis-gears_test.go
Labels: bug

#151 Refactoring Query Editor
  src/components/query-editor/query-editor.test.tsx
  src/components/query-editor/query-editor.tsx
  src/redis/types.ts
Labels: enhancement

#152 Add handling different frame type for Streaming data source
  provisioning/dashboards/data-types.json
  src/components/query-editor/query-editor.tsx
  src/constants.ts
  src/data-source.test.ts
  src/data-source.ts
  src/frame-formatters/data.test.ts
  src/frame-formatters/data.ts
  src/frame-formatters/index.ts
  src/frame-formatters/time-series.test.ts
  src/frame-formatters/time-series.ts
  src/redis/types.ts
Labels: enhancement

#155 Update tooltip for RedisTimeSeries Label Filter
  provisioning/dashboards/data-types.json
  src/components/query-editor/query-editor.tsx
Labels: enhancement
