Repository RedisGrafana/grafana-redis-datasource, pull requests merged in 2021-02, with the labels that each got.

#159 Fix TS.INFO error for simple string values.
  pkg/datasource_test.go
  pkg/redis-time-series.go
  pkg/redis-time-series_integration_test.go
  pkg/redis-time-series_test.go
Labels: bug

#160 Update Grafana SDK 0.86 to fix race conditions
  go.mod
  go.sum
  package.json
Labels: bug

#157 Add Redis Graph module (GRAPH.QUERY, GRAPH.SLOWLOG)
  data/dump.rdb
  pkg/query.go
  pkg/query_test.go
  pkg/redis-graph.go
  pkg/redis-graph_integration_test.go
  pkg/redis-graph_test.go
  pkg/types.go
  provisioning/dashboards/data-types-7.4.json
  src/redis/command.ts
  src/redis/query.ts
Labels: enhancement

#162 Update CHANGELOG and README
  CHANGELOG.md
  README.md
Labels: documentation

#163 Update Plugin sign process
  .github/workflows/main.yml
  package.json
Labels: enhancement

#164 Update Grafana dependencies to 7.4.2
  CHANGELOG.md
  package.json
  yarn.lock
Labels: enhancement
